{"name": "Тест на получение ошибки приняти заказа c неверным id курьера", "status": "passed", "start": 1745008113896, "stop": 1745008114301, "uuid": "16000960-31ef-4468-a7b6-321e561ea55c", "historyId": "cc198d8d2a88e0a22daf1d39b857b463", "testCaseId": "cc198d8d2a88e0a22daf1d39b857b463", "fullName": "tests.test_accept_the_order.TestAcceptOrder#test_accept_order_invalid_courier_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-3QFAQEQR"}, {"name": "thread", "value": "8104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}