{"name": "Тест на получение ошибки приняти заказа c неверным id курьера", "status": "passed", "start": 1745072123660, "stop": 1745072124033, "uuid": "324566cd-f39c-430f-b04e-e5c4e40f1613", "historyId": "cc198d8d2a88e0a22daf1d39b857b463", "testCaseId": "cc198d8d2a88e0a22daf1d39b857b463", "fullName": "tests.test_accept_the_order.TestAcceptOrder#test_accept_order_invalid_courier_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-3QFAQEQR"}, {"name": "thread", "value": "10504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}